spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TEST

    username: postgres
    password: SA12nya3@

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true